version: '3'
  
services:
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5123:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ims
